chore: multiple development branches

diff --git a/actions/semantic_versioning/action.yml b/actions/semantic_versioning/action.yml
--- a/actions/semantic_versioning/action.yml
+++ b/actions/semantic_versioning/action.yml
@@ -3,6 +3,9 @@ name: Calculate Version
 description: Calculate semver-format version based on current branch name and existing tags in git repository
 
 inputs:
+  filter-version:
+    description: Operate within versions matched regex
+    default: '[0-9]+\.[0-9]+'
   promote:
     description: When "true", skips RC increment and produces stable X.Y.Z tag instead. Works only on `release-*` branches
     default: "false"
@@ -87,8 +90,12 @@ runs:
 
         git fetch --tags
 
-        LATEST_STABLE_TAG=$(git tag | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$" | sort -V | tail -1 || true)
-        LATEST_RC_TAG=$(git tag | grep -E "^[0-9]+\.[0-9]+\.0-rc\.[0-9]+$" | sort -V | tail -1 || true)
+        if [ -z "${INPUT_FILTER_VERSION}" ]; then
+          INPUT_FILTER_VERSION="[0-9]\.[0-9]+"
+        fi
+        LATEST_STABLE_TAG=$(git tag | grep -E "^${INPUT_FILTER_VERSION}\.[0-9]+$" | sort -V | tail -1 || true)
+        LATEST_STABLE_TAG_WITHOUT_FILTER=$(git tag | grep -E "^[0-9]\.[0-9]\.[0-9]+$" | sort -V | tail -1 || true)
+        LATEST_RC_TAG=$(git tag | grep -E "^${INPUT_FILTER_VERSION}\.0-rc\.[0-9]+$" | sort -V | tail -1 || true)
 
         if [[ "${CURRENT_BRANCH}" == "development" ]]; then
           # Determine which is greater: latest stable tag or latest RC tag
@@ -137,6 +144,18 @@ runs:
               ;;
           esac
 
+        elif [[ "${CURRENT_BRANCH}" =~ ^development- ]]; then
+          DEVELOPMENT_LINE="${CURRENT_BRANCH##development-}" # e.g. "1.0"
+          if [ $(git tag | grep -cE "^$(echo $DEVELOPMENT_LINE | awk -F. '{print $1"\."$2}')") -gt 0 ]; then
+            CURRENT_VERSION="${LATEST_STABLE_TAG}"
+            DEV_N=$(git rev-list --count "${LATEST_STABLE_TAG}..HEAD")
+            NEXT_VERSION=$(bump_version "${CURRENT_VERSION}" --minor --pre-release "-dev.${DEV_N}")
+          else
+            CURRENT_VERSION="${DEVELOPMENT_LINE}.0"
+            DEV_N=$(git rev-list --count "${LATEST_STABLE_TAG}..HEAD")
+            NEXT_VERSION=$(bump_version "${CURRENT_VERSION}" --pre-release "-dev.${DEV_N}")
+          fi
+
         elif [[ "${CURRENT_BRANCH}" =~ ^release- ]]; then
           RELEASE_LINE="${CURRENT_BRANCH##release-}" # e.g. "1.0"
           STABLE_TAG=$(git tag | grep -E "^${RELEASE_LINE}\.[0-9]+$" | sort -V | tail -1 || true)
@@ -146,7 +165,7 @@ runs:
             CURRENT_VERSION="${STABLE_TAG}"
             NEXT_VERSION=$(bump_version "${CURRENT_VERSION}" --patch)
             IS_RELEASE="true"
-            if [ "$(version "${NEXT_VERSION}")" -gt "$(version "${LATEST_STABLE_TAG}")" ]; then
+            if [ "$(version "${NEXT_VERSION}")" -gt "$(version "${LATEST_STABLE_TAG_WITHOUT_FILTER}")" ]; then
               IS_LATEST="true"
             fi
 
@@ -156,7 +175,7 @@ runs:
             NEXT_VERSION="${RELEASE_LINE}.0"
             CHANGELOG_MODE="merge-base"
             IS_RELEASE="true"
-            if [ "$(version "${NEXT_VERSION}")" -gt "$(version "${LATEST_STABLE_TAG}")" ]; then
+            if [ "$(version "${NEXT_VERSION}")" -gt "$(version "${LATEST_STABLE_TAG_WITHOUT_FILTER}")" ]; then
               IS_LATEST="true"
             fi
 
@@ -177,7 +196,7 @@ runs:
           fi
 
         else
-          echo "::error::Unsupported branch name '${CURRENT_BRANCH}'. Only 'development' and 'release-X.Y' branches are supported"
+          echo "::error::Unsupported branch name '${CURRENT_BRANCH}'. Only 'development', 'development-X.Y' and 'release-X.Y' branches are supported"
           exit 2
         fi
 
@@ -221,4 +240,5 @@ runs:
         echo "release-line=${RELEASE_LINE:-}" >>$GITHUB_OUTPUT
         echo "changelog-mode=${CHANGELOG_MODE}" >>$GITHUB_OUTPUT
       env:
+        INPUT_FILTER_VERSION: ${{ inputs.filter-version }}
         INPUT_PROMOTE: ${{ inputs.promote }}
